version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
        environment:
            KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "Stocks:2:1,Quotes:2:1,Orders:2:1"